#!/bin/sh
### BEGIN INIT INFO
# Provides:          doptrackwebappserver
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Remote\ server\ part\ of\ webapp\,\ using\ doptrack\ scripts
### END INIT INFO

###  NOTE: Inhoud van restartService.sh  moet worden overgenomen in dit script.     
#   mv "/webappservercontrol" "/etc/init.d/doptrackwebappserver"
#   chmod +x /etc/init.d/doptrackwebappserver
#   sudo touch "/var/log/doptrackwebappserver.log" && sudo chown "rvandenberg" "/var/log/doptrackwebappserver.log"
#   sudo touch "/var/log/pythonDoptrackServer.log" && sudo chown "rvandenberg" "/var/log/pythonDoptrackServer.log"
#   sudo update-rc.d "doptrackwebappserver" defaults
#   sudo service "doptrackwebappserver" start


SCRIPT="python /opt/doptrackwebappserver/DoptrackControlService.py"
RUNAS=rvandenberg

PIDFILE=/var/run/doptrackwebappserver.pid
LOGFILE=/var/log/doptrackwebappserver.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi

  echo '1 Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"  
  su -c "$CMD" $RUNAS > "$PIDFILE"
  
  echo "running services:"
  ps -ef | grep 'DoptrackControlService.py\|DoptrackMonitorService.py\|ReceiverService.py'

  echo "processID"
  cat $PIDFILE

  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f doptrackwebappserver remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac

